[package]
name = "chopper"
version = "0.3.0"
authors = ["wdecoster <decosterwouter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
clap = { version = "3.2.6", features = ["derive"] }
rayon = "*"
approx = "*"
minimap2 = "0.1.10"
